Audionut/Upload-Assistant

- src/trackers/BLU.py
Added OFT to the list of banned groups on BLU.
> Added OFT to BLU Banned groups

- data/example-config.py
- src/args.py
- src/prep.py
Add support for PT Screens image host
Image host centered around private trackers, no API limits or size constraints.
> Add support for PT Screens image host

- src/trackers/ACM.py
Fixes https://github.com/Audionut/Upload-Assistant/issues/6
> FIX - acm url

- data/example-config.py
- src/prep.py
Fixes https://github.com/Audionut/Upload-Assistant/issues/3
> FIX - manual edition

- src/args.py
- src/clients.py
- src/prep.py
- upload.py
> Allow keep folder

- src/prep.py
- src/trackers/MTV.py
Remove unnecessary console messages
> FIX - image reuploading funtions

- src/prep.py
Fixes https://github.com/Audionut/Upload-Assistant/issues/29
> Fix imgbox uploads

- src/trackers/AITHER.py
Should resolve https://github.com/Audionut/Upload-Assistant/issues/31
> Nonestype string error on subs

- Dockerfile
- requirements.txt
Downgrades pymediainfo so dvd mediainfo contains languanges.
> Fixes full disk dvd mediainfo

- src/prep.py
Fixes https://github.com/Audionut/Upload-Assistant/issues/62
Update the image upload handling to retry on failed connection to catch minor connection interruption.
Log successful image upload to ensure that the entire image set is not (re)uploaded upon image host switch.
Trying to find the best compromise between allowing enough time for slower connections to work, and keeping things snappy.
This seems like the best compromise, will only trigger on connection error, and was better than the previous handling, especially for some.
1. Retry Attempt 1:
- Backoff time = 10 * (1.7 ** 0) + random.uniform(0, 1)
- Backoff time = 10 + random.uniform(0, 1)
- Result: 10-11 seconds (including jitter).
2. Retry Attempt 2:
- Backoff time = 10 * (1.7 ** 1) + random.uniform(0, 1)
- Backoff time = 17 + …
> Update image host retry logic

- data/example-config.py
- src/args.py
- src/prep.py
> Add OnlyImage Support

- upload.py
Site doesn't support it (yet) and it's causing issues for users using this currently
> Removing ULCX as modq capable

- src/args.py
- src/prep.py
- upload.py
This contains the fixes described in issue 53.
> Dual audio Fixes for issue 53

- src/prep.py
OS pathsize:
``` python
"https://images2.imgbox.com/7c/85/RIxa5mWn_o.png": 678054,
"https://images2.imgbox.com/43/38/kQgEjvZV_o.png": 694029,
"https://images2.imgbox.com/75/15/URG7yGxB_o.png": 633713,
"https://images2.imgbox.com/64/54/7Rwf1o41_o.png": 793729,
"https://images2.imgbox.com/04/73/BYeU7ThX_o.png": 684241,
"https://images2.imgbox.com/7a/47/s6QXeDgK_o.png": 760642
```
Uploaded image size:
``` python
"https://images2.imgbox.com/cd/7e/TU4dY5hO_o.png": 1180295,
"https://images2.imgbox.com/43/db/HGlGqX2g_o.png": 1064393,
"https://images2.imgbox.com/7f/39/JSNRLtwh_o.png": 1085552,
"https://images2.imgbox.com/61/a6/6Gk2EKTJ_o.png": 1051502,
"https://images2.imgbox.com/50/82/lc5n3zfk_o.png": 1071323,
"https://images2.imgbox.com/31/4e/6TRQDcgE_o.png": 1177370
```
Fixes more further …
> imgbox modifies files

- data/example-config.py
- src/trackers/SPD.py
- upload.py
adding speedapp
I cant promise this will work as its been over a year since i last uploaded here but if not most of the work is done for someone else to update.
> adding speedapp

- src/args.py
fixes missing DCP sources
https://github.com/Audionut/Upload-Assistant/issues/101
> Add DCP source support

- data/example-config.py
Update with missing trackers and aligned to alphabetical order to make it easier to read.
- TTG
- JPTV
- etc
This should also close https://github.com/Audionut/Upload-Assistant/issues/41
Not sure if there any reason not to include some but I've added them all in.
> Add example tracker and alphabetical order.

- src/trackers/COMMON.py
The use of the Space at the end of each screenshot would cause for formatting issues when going to new lines as there would be a trailing space with bbcode, please reach out if screens are needed.
> Update COMMON.py For Screenshot Formating

- src/trackers/NBL.py
Changing the use from the full MEDIAINFO.txt to the MEDIAINFO_CLEANPATH.txt to clean up uploads
> Update NBL.py to use CLEANPATH

- upload.py
https://github.com/Audionut/Upload-Assistant/issues/136
> Don't overwrite traceback

- src/prep.py
> Multiprocess screenshots

- src/prep.py
- src/trackers/MTV.py
- upload.py
> Multiprocess uploads

- src/args.py
- src/prep.py
- upload.py
fixes https://github.com/Audionut/Upload-Assistant/issues/150
> Manual type fix

- src/trackers/MTV.py
fixes https://github.com/Audionut/Upload-Assistant/issues/152
> MTV cleanup - fixes manual mode

- src/prep.py
> Ugly abort if image host fail

- src/trackers/BHD.py
fixes https://github.com/Audionut/Upload-Assistant/issues/160
> BHD image rehosting

- src/trackers/COMMON.py
> Duping - search name not uuid

- src/prep.py
hopefully fixes https://github.com/Audionut/Upload-Assistant/issues/156
based on https://api.imgbb.com/
> fix for imgbb

- src/prep.py
Even with the correct ID inputs, sometimes the wrong tvmaze id is returned because TV is a clusterfuck.
This PR allows the user to select from a list of different tvmaze search results, returning the correct id. Probably only really helpful for those blastered daily shows, so it requires `--daily` specified to allow selection.
> Allow select tvmaze id

- requirements.txt
- src/trackers/BHD.py
Need some mapping to link urls with host
> BHD - imgbb = ibb.co

- src/args.py
- src/prep.py
See https://github.com/Audionut/Upload-Assistant/issues/179
> Add tvmaze and tvdb arguments

- src/prep.py
Might fix https://github.com/Audionut/Upload-Assistant/issues/181
> DVD - select longest vob for screens

- src/prep.py
Only file based screens for now, waiting for feedback.
Might fix https://github.com/Audionut/Upload-Assistant/issues/184
> Try detect TTY and use minimal progress bars

- src/trackers/HUNO.py
Proper fix for https://github.com/Audionut/Upload-Assistant/issues/143
> Robust language checking

- src/prep.py
Should fix or help mitigate https://github.com/Audionut/Upload-Assistant/issues/193
> Add framerate as a dvd system fallback method

- src/prep.py
Will stop matching against video codec, region etc.
> Require - for tag with bdmv

- src/args.py
- src/prep.py
Messy code with all console prints still present.
MOVIE - before/after:
Metadata processed in 15.62 seconds
Metadata processed in 6.23 seconds
TV - before/after:
Metadata processed in 19.07 seconds
Metadata processed in 8.41 seconds
> refactor IMDB handling

- src/prep.py
- src/trackers/HHD.py
> ADD - HHD support

- src/trackers/PTP.py
- src/trackers/SN.py
adding parsing of URLs on SN and PTP.
I tested SN but dont have any files to upload to PTP to test with.
> adding parsing of URLs

- requirements.txt
> add aiofiles to requirements.txt

- README.md
- data/example-config.py
- src/trackers/FRIKI.py
- src/trackersetup.py
- src/uploadscreens.py
> ADD FRIKI (Tracker) + ADD DALEXNI (Image/Video Hosting)

- .gitignore
- src/trackers/AITHER.py
- src/trackersetup.py
- src/trackerstatus.py
Only Aither currently supported.
Checks once per week.
> Banned groups from API

- data/example-config.py
- src/trackers/HDT.py
> fixing HDT and updating example

- src/imdb.py
- src/trackers/RTF.py
Also grab episode data from IMDB.
Example:
```python
{
'imdbID': '11280740',
'title': 'Severance',
'year': 2022,
'aka': 'Severance',
'type': 'tvSeries',
'runtime': '50',
'cover': 'https://m.media-amazon.com/images/M/MV5BZDI5YzJhODQtMzQyNy00YWNmLWIxMjUtNDBjNjA5YWRjMzExXkEyXkFqcGc@._V1_.jpg',
'plot': 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about
their jobs.',
'genres': 'Drama, Mystery, Sci-Fi, Thriller',
'rating': 8.7,
'directors': [],
'episodes': [
{'id': 'tt11650328', 'title': 'Good News About Hell', 'release_year': 2022, 'release_date': {'year': 2022, 'month': 2, 'day': 18}},
{'id': 'tt13393872', 'title': 'Half …
```
> Imdb episodes

- data/example-config.py
- src/rehostimages.py
- src/takescreens.py
- src/trackers/BHD.py
- src/trackers/MTV.py
- src/trackers/OTW.py
- src/uploadscreens.py
Remove duplicate code from site files.
In preparation of pending ptpimg changes.
Significantly easier to PR site based image host needs.
todo:
> Image rehosting refactor

- src/trackers/AITHER.py
- src/trackers/BHD.py
- src/trackers/COMMON.py
> Add size variable to dupe checking

- src/uploadscreens.py
Uploaded images get spammed to the host when pooling, and can be returned in any order.
Add an index to track the images, ensuring the image list retains runtime order
> Add index to uploaded images

- README.md
- data/example-config.py
- src/trackers/ITT.py
- src/trackersetup.py
Please add this italian tracker :)
> add ITT tracker

- src/trackers/AITHER.py
- src/trackers/BHD.py
- src/trackers/BLU.py
- src/trackers/CBR.py
- src/trackers/COMMON.py
- src/trackers/FNP.py
- src/trackers/FRIKI.py
- src/trackers/HHD.py
- src/trackers/HUNO.py
- src/trackers/ITT.py
- src/trackers/JPTV.py
- src/trackers/LCD.py
- src/trackers/LST.py
- src/trackers/LT.py
- src/trackers/NBL.py
- src/trackers/OE.py
- src/trackers/OTW.py
- src/trackers/PSS.py
- src/trackers/PTT.py
- src/trackers/R4E.py
- src/trackers/RF.py
- src/trackers/SHRI.py
- src/trackers/SN.py
- src/trackers/SP.py
- src/trackers/STC.py
- src/trackers/ULCX.py
- src/trackers/UNIT3D_TEMPLATE.py
- src/trackers/UTP.py
- src/trackers/YOINK.py
- Don't pre-filter with episode as it excludes season packs from being returned when uploading episode
- Dupe check episodes against season packs.
> Season episode dupe checking

- src/trackers/COMMON.py
Extending the multi file handling code with the previously added screenheader code to align the output experience.
> Adding screenheader code to multi files

- src/trackers/LT.py
Adds more Spanish audio to the checks.
Fixes incorrect `[SUBS]` in titles
> Update LT.py: Add more Spanish audio checks

- src/trackers/FNP.py
> Update FNP.py (resolution_id)

- requirements.txt
- src/discparse.py
- src/prep.py
Make it work better.
Will close https://github.com/Audionut/Upload-Assistant/issues/299
> HDDVD updates

- requirements.txt
- src/args.py
- src/prep.py
> add argument -oil, only if language present

- src/takescreens.py
- src/trackersetup.py
- src/uploadscreens.py
tqdm leaves lingering threads no matter what I tried, so switching to rich progress instead.
Notice that tracker_status/search_existing is leaving asyncio threads also, so will  be cleaned.
Hopefully will fix https://github.com/Audionut/Upload-Assistant/issues/268
> Fix outstanding threads

- src/trackers/OTW.py
- src/uphelper.py
OTW remove aka
meta summary type fixes
> misc fixes

- src/trackermeta.py
- src/trackers/HUNO.py
- src/trackers/MTV.py
- src/trackers/OE.py
fixes https://github.com/Audionut/Upload-Assistant/issues/317
> Handle all prompts in -ua

- data/example-config.py
- requirements.txt
- src/clients.py
Add support for Transmission. Tested adding torrents to the downloader and torrent_storage_dir.
> feat: support transmission

- src/getseasonep.py
- src/prep.py
- src/tmdb.py
- src/tvmaze.py
Clean up id handling and ensure inputted ids into prep do not get overwritten,
> Don't overwrite ids

- src/trackers/JPTV.py
> JPTV - add torrent url

- src/prep.py
Add support for Proper2 and Proper3.
> Add proper2 and proper3 support

- src/prep.py
Adding 2 and 3 to PROPER to correct the naming as expected.
> Correcting PROPER number namings in title

- src/cleanup.py
- upload.py
> move cleanup to file

- README.md
- data/example-config.py
- src/trackers/TOCA.py
- src/trackersetup.py
Already tested and it is working.
> Added support for TocaShare

- src/trackers/SP.py
Use generated name instead of folder name for anime uploads.
> Update naming logic for SP Anime Uploads

- src/trackers/ITT.py
Fixed the torrent comment using another tracker link.
> Fix ITT torrent comment

- src/trackers/LT.py
This tracker does not have any registered distributor.
> LT - fix no distributor api endpoint

- src/trackers/TOCA.py
I remade it using "UNIT3D_TEMPLATE.py", it's a bit cleaner. I tested it and it's working as intended.
> Refactor TOCA.py

- src/exportmi.py
- src/prep.py
fix as 960x540 seems to be marked as 1024x540 so gets marked 576
> update to improve 540 detection

- data/example-config.py
- src/bbcode.py
- src/btnid.py
- src/prep.py
- src/trackermeta.py
BHD added folder_name searching, it's worth running auto searches since they are now one of 3 sites to support folder name searching.
> BHD - file/folder searching

- src/prep.py
> group tag regex

- src/prep.py
- src/tmdb.py
Use secondary title if needed in tmdb search
> Better title/year parsing for tmdb searching

- data/example-config.py
- src/clients.py
- src/prep.py
- src/trackers/COMMON.py
- src/tvdb.py
- src/tvmaze.py
- upload.py
for the lazy like me, this will auto pull the torrent data from qBitTorrent v5+ from just the path, no `-th` or `--infohash` or `--XXX` where XXX is a site, needed.
> qBitTorrent auto torrent grabing and rTorrent infohash support

- data/example-config.py
- src/clients.py
This needs testing by someone with rTorrent. Will push a docker with the branch name as tag
> add rTorrent linking support

- src/trackers/AL.py
Updated AL.py based on newer UNIT3D_TEMPLATE.py and tracker's naming matrix.
> Updated AL upload

- src/trackers/PSS.py
From mod:
> has no release group name on the upload, please add -NoGrP or -NOGROUP at end of those without a release group name.
> Add tag for releases without a group name (PSS)

- src/cleanup.py
might fix https://github.com/Audionut/Upload-Assistant/issues/464
> handle cleanup on mac os without termination

- src/trackers/CBR.py
Also added the -NoGroup tag where applicable, as it is a tracker rule.
> Refactor CBR.py

- data/example-config.py
- src/args.py
- src/clients.py
- src/prep.py
- src/trackermeta.py
- src/trackers/COMMON.py
- src/trackers/HUNO.py
- upload.py
Initial intent is to try and find region/distributor ids automatically.
adds HUNO and ULCX as tracker options
> store and use any found torrent data

- src/trackers/TVC.py
Updating TVC as it now allows 1080p HEVC.
> TVC Allow 1080p HEVC

- src/trackers/AL.py
- Added '-' before "NoGroup" when tag is empty
- Adjusted disc audio languages formatting to be the same as non-disc releases
- Adjusted audio mono channel to show as "1.0" instead of only "1"
> Small fixes to AL title formatting

- src/region.py
I've seen ADN being used as a source more and more recently, since they have proper English subtitles for anime, instead of "dubtitles"
> Adding ADN as a provider

- src/region.py
Updated the service mapping for NOW to also include NOWTV
> Update Service Mapping NOW

- src/trackers/HDB.py
Corrected a small typo in HDB comps.
Thanks again for the enhancement.
> Fix typo in HDB comps

- src/prep.py
Extracted scene releases can be all lowercase, which results in bad group tags.
Some scene releases also don't have extracted content names matching release names.
This catches both.
> Check lowercase names against srrdb for proper tag

- src/trackers/CBR.py
- removes the year from title when category is TV Show or Anime
- changes the way AKA titles are handled
> CBR - aka and year updats for name

- src/trackers/PSS.py
> Update PSS banned release groups

- src/trackers/OTW.py
> Update OTW banned release groups

- src/prep.py
> Use TVDB title

- src/bbcode.py
- src/trackermeta.py
- src/trackers/HDB.py
Only tested with `767407` so far, which gives expected results.
> HDB descriptions

- src/rehostimages.py
There was an instance where the function was failing to find *any* png files whilst referencing the correct tmp directory.
This adds a final fallback that navigates into the tmp directory, and then globs from there.
> Image rehosting use os.chdir as final fallback

- data/example-config.py
- src/trackers/CBR.py
Enabling modq option. CBR now supports modq.
> CBR - Initial modq setup

- src/trackers/AL.py
Updated get category function to identify H-Anime
> Updated get category function

- README.md
- data/example-config.py
- src/trackers/BT.py
- src/trackersetup.py
BrasilTracker is a brazilian Private Torrent Tracker for MOVIES / TV / GENERAL based on the gazelle framework.
> Added support for BrasilTracker

- src/trackers/ULCX.py
Niblets, Vyndros, INFINITY, FRDS, VXT were just added.
> (Update) ULCX banned groups

- src/trackers/UTP.py
Fix hardcoded tracker name for UTP upload
> Fix upload to UTP

- src/queuemanage.py
Check the directory, find any changes and option to update the existing log.
Uses existing by default in unattended, run once without to update.
> queue update

- src/args.py
- src/tmdb.py
Graceful exception handling.
Better parsing support for multiple input types.
> Robust id from mediainfo

- src/imdb.py
This will be very useful for BT (and BJS which I'm currently working on), tmdb has been pretty spotty for these types of data
> imdb - get more crew info

- src/languages.py
Will also now print the track number when prompting.
> Get language from track title

- src/clients.py
- upload.py
gets the trackers that match the content and remove from meta['trackers'] if present
> remove trackers found in client

- src/region.py
https://en.wikipedia.org/wiki/Pirated_movie_release_types#Common_abbreviations_for_digital_platforms
> Add service Chorki

- data/Upload-Assistant-release_notes.md
- data/example-config.py
- src/takescreens.py
- src/trackers/RF.py
- upload.py
Tonemapping for profile 5 dolby vision and HLG files.
Requires recent ffmpeg.
> Option - libplacebo tonemapping

- src/trackers/FNP.py
From https://fearnopeer.com/wikis/4
> [FnP] Fix resolutions, types and add banned release groups

- data/example-config.py
- src/args.py
- src/trackers/SPD.py
- upload.py
Fix:
- Incorrect category mapping
Changes:
- Use only httpx
- Create the torrent locally instead of downloading it from the website
- Add support for the new channels section
- Send additional fields such as plot, NFO, description, etc.
- Add Romanian categories
> SPD - fix and changes

- src/trackers/HDB.py
Updates HDB.py to clean size bbcode as [size] is not valid in HDB descriptions
> Update HDB.py to clean size bbcode

- src/trackers/FNP.py
> FNP - fix banned groups

- src/trackers/ULCX.py
> Update to banned groups ULCX.py

- src/trackers/FNP.py
> FNP - remove a group for banned release groups

- .gitignore
I added the venv and .venv directories to the .gitignore file
> add venv to .gitignore

- src/trackers/SHRI.py
Remove 'Dubbed' from title if present, add [SUBS] tag when no Italian audio track is found but Italian subtitles are available.
> Remove 'Dubbed', add [SUBS] tag

- data/example-config.py
- src/trackers/HDT.py
An attempt to fix upload issues
> refactor(HDT)

- src/prep.py
- src/trackers/AZ.py
- src/trackers/BJS.py
- src/trackers/BT.py
- src/trackers/DC.py
- src/trackers/GPW.py
- src/trackers/PHD.py
- src/video.py
I think using the largest file to determine the container is the easiest way. Let me know if there is a better way.
> add(meta): video container

- src/trackers/HDT.py
- src/trackerstatus.py
fixes https://github.com/Audionut/Upload-Assistant/issues/836
> HDT - auth token availability

- data/example-config.py
- src/bluray_com.py
- src/get_name.py
- src/prep.py
- src/trackers/COMMON.py
- src/trackers/UNIT3D.py
Trigger bluray_com.py to scrape for distributor, region, and cover images when uploading a DVD full disc.
> Add support for bluray.com scraping for DVDs

- data/example-config.py
- src/clients.py
- src/prep.py
See https://github.com/autobrr/qui#reverse-proxy-for-external-applications
> add support for qui reverse proxy

- src/trackers/ULCX.py
> Update to ULCX banned groups
