Audionut/Upload-Assistant

src/prep.py

Added the ability to support proper identification of Dubbed/Dual Audio for Spanish audio tracks.

Catch for Spanish dubbed/dual-audio spanish

---

src/prep.py
src/trackers/ANT.py
src/trackers/MTV.py
upload.py

ANT has realistic piece count + .torrent size requirements for uploaded .torrents, this code change respects those requirements.
Existing torrent hashes are not affected by this change, but all newly created torrents and torrents needed for ANT will use the following constraints:
```Piece count between 1000 & 2000 pieces with a .torrent size < 100 KiB.```
Perhaps in the future I might add an argument allowing override.

Allow piece size > 16 MiB

---

.github/workflows/docker-image.yml
.github/workflows/lint.yml
src/args.py
src/bbcode.py
src/prep.py
src/trackers/COMMON.py

Feel free to push extra sites for ID searching, but I'm not keen on any other sites being auto searched unless they are known for quality descriptions.
Currently, only HDB has good folder matching, UNIT3D sites should give exact matches once https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/4113 is implemented.
todo: 
- Fuzzy match folders with PTP
- Consider parsing HDB descriptions.

Unit3d searching

---

README.md
data/example-config.py
src/trackers/PSS.py
upload.py

After getting guidance from #37 have added the new tracker through the unit3d template. Think I have everything in order.

Added new tracker PSS

---

src/prep.py

fixes https://github.com/Audionut/Upload-Assistant/issues/56
If --service is argumented, service_longname is not set in the meta causing error https://github.com/Audionut/Upload-Assistant/blob/69c0bce2a025444a538eddeccb281c3e5b4529ba/src/trackers/MTV.py#L372
I'm really lost as to what the intended purpose was here. If I just keyed like the existing logic, it would key from the first key, and  just use CR, being the first key, instead of the services long name, Crunchy Roll, (since every service long_name key is duplicated from an abbreviated service key).
If I manually set --service "Crunchy Roll", then it would use "Crunchy Roll" for both the service and service_longname meta.
What on earth was the purpose of service_longname if it's just set as the abbreviated service name.......And if …

define service_longname when service specified

---

data/example-config.py

Setting defaults for API to False where they were true to prevent issues with API calls when not on those sites.
Removed a line for ULCX of a function not in use that shouldn't be in the example-config

Set default API to False and remove ULCX modq option from example-config

---

src/trackers/HUNO.py

Web encodes used to get labelled as 'WEB' even when forced `-type encode` was passed.
Now, it checks `video_encode` gathered by [prep.py](https://github.com/Audionut/Upload-Assistant/blob/master/src/prep.py), instead of `basename`, which is more accurate.
Removed redundant `basename` declaration.

HUNO web type fix

---

data/example-config.py
src/prep.py

Fix for: https://github.com/Audionut/Upload-Assistant/issues/88
- Limits to half of available CPU cores when optimizing images with oxipng
- adds new option to the config called "shared_seedbox" to enable this feature as it slows down speed of which screenshots are taken.

option to limit thread usage during optimize_images

---

upload.py

Adding in Shebang support, This removes the need to declare python3 when running the script on Linux or in docker.
`#!/usr/bin/env python3`
It a minor change but saves a small bit of typing.

Add-Shebang-Support

---

.github/workflows/docker-image.yml
src/trackers/COMMON.py

Some API's don't return type, which means remux will match as dupe against non-remux, web against bluray, etc, etc.
This PR attempts to add some extra checking to filter out these clear false results from the dupe check.
Existing:
``` python
Searching for existing torrents on site...
[09:47:36] Pre-filtered dupes                                                                                                                                                        COMMON.py:380
[                                                                                                                                                                         COMMON.py:381
'Training.Day.2001.PROPER.576p.BluRay.x264.AC3.5.1-TBB.mkv',
'Training.Day.2001.1080p.UHD.BluRay.DDP7.1.HDR10.x265-c0kE.mkv', …
```

Update dupe checking

---

.gitignore
src/prep.py
upload.py

This PR should address a few issues:
1. Added a regular expression check that will treat all uploads with YYYY.XX.XX or YYYY-XX-XX in the filename as if that date has been supplied to the --daily argument
2. Corrected small bug in tmdb season/episode matching against air date
3. When generating the torrent name, daily episodes will drop the SXX EXX format, and instead use the air date from step one above. Season and episode are still sent to the tracker and therefore used in the UI, just not included in the torrent title/name.
4. (Tangentially related) Display the TVmaze ID during the upload confirmation
Overall, these changes should provide flexibility when uploading daily episodes, depending on the preferences of the trackers.
On gazelle-based trackers, or for UNIT3D sites where the …

Improved handling of daily TV episodes

---

src/trackers/COMMON.py

The required string conversion for IMDB ID because unit3d has dorky imdb handling, means this can return a string of 0's instead of None, which set the IMDB meta as a string of 0's.
fixes: https://github.com/Audionut/Upload-Assistant/issues/185

UNIT3D set ID to none if 0

---

src/prep.py

Uses the following logic:
- If the file has video bitrate (or overall bitrate for old versions of MediaInfo) of **8000kbps** (higher for overall), it’s WEB-DL from CR (CR always encode 1080p releases with rc=2pass and constant video bitrate of **8000kbps**)
- If the file has video bitrate lower than 8000kbps (same `rc=2pass` with constant video bitrate **~5000kbps**, varies between shows, no higher than **5372kbps**), it’s WEB-DL from HIDI
- SP only grab releases from CR or HIDI.
Caveat: Identifying streaming services for **720p** SP releases isn't implemented as I don't see any demand for that resolution (and to keep things simple). Similar logic with lower resolution and halved video bitrate.

Identify streaming services for SubsPlease releases

---

src/trackers/BHD.py

Adds some spaces for screenshots in description so they looks like [this](https://imgbox.com/cyR7TFGj), instead of [this](https://imgbox.com/jSIWjlxg). I only updated BHD config, I'd imagine it'd be similar on other trackers that uses BBCode (if other trackers prefer this format). This works well in *x2 format (any number of rows and 2 columns), which most uploads use.
I used [align=center] instead of [center], so that if preferred left/right-aligned, the alignment can be changed in one place (as opposed to changing both opening and closing tag.

Added some spaces between screenshots in description

---

src/trackers/HDB.py
src/trackers/PTP.py

Fix torrent creation PTP-HDB

---

src/args.py
src/prep.py

SP releases never have episode title and titles are mistaken as episode title in some cases so don’t try to guess it. Simple addition to existing SP tag check. 
PS: Maybe a flag to skip episode title guess would be better since some other groups’ releases don’t have episode titles and the flag would prevent `guessit` from getting it wrong altogether.

Add -met/--manual-episode-title to set episode title, allow to set empty episode title

---

src/clients.py
src/trackers/COMMON.py

this prevents exposing private info that could be in a comment when BASE.torrent is created manually.
adding a bit more info to torrent piece size verification to help with selection if you have multiple torrents to reuse. Changing output to RED to make it easier to see why passed torrent failed verification.

adding blank comment to any uploaded torrent created from BASE.torrent

---

src/trackers/BHD.py
src/trackers/MTV.py
src/trackers/OTW.py

When site files need images reuploaded, save to json file and reuse where needed, without each site file potentially reuploading images to the same host.

save reuploaded images

---

src/args.py
upload.py

Deleting the meta.json is useful when you need a metadata refresh, but need to keep existing taken images and such.
Not as intrusive as cleanup which kills the entire tmp directory.
Should be most useful for remote installations where accessing the folder is more painful than a simple argument.

add argument delete meta.json

---

src/trackersetup.py
src/trackerstatus.py

Laying down the groundwork to check claims at Aither, and skip claimed content without needing to be told by the upload endpoint.

Get tracker claims

---

src/discparse.py
src/prep.py
src/trackers/COMMON.py
src/trackers/PTP.py
src/uploadscreens.py

Use playlists instead of scanning the entire disc.
```python
Available playlists:
[0] 00000.mpls - 1h 25m 10s - 00000.m2ts (24475 MB)
[1] 00002.mpls - 0h 24m 26s - 00003.m2ts (5956 MB)
[2] 00006.mpls - 1h 33m 24s - 00007.m2ts (5093 MB)
[3] 00010.mpls - 0h 9m 22s - 00011.m2ts (1827 MB)
Enter playlist numbers separated by commas, or 'ALL' to select all:
```
The longest and/or first playlist in the full scan is not always correct. This PR allows the user to select the correct playlist, else will select the largest playlist in unattended. The full scan was only ever parsed to get the playlist anyway.
Will have the side benefit of being quicker to process BD.
Multi-discs select the largest playlist, fancy playlist support for multi-disc may come later.

BD Disc - use playlists

---

src/trackers/MTV.py

It's not required by MTV rules, but it's very much needed. And it will bring consistence with UNIT3D uploads.

[MTV.py] Adding second mediainfo for DVD .vob files where applicable.

---

src/prep.py
upload.py

During the refactor of the process in V2, one unintended consequence was background looping of the tracker_status process, resulting in tracker confirmation prompts equaling the amount of times meta was edited via `is this correct`.
This refactor seeks to unfuck things.
Will also attempt to refactor the edit arg process to properly track original and edited meta. ie: If someone specifies an argument to be modified, that argument should stick, even if the arguments are modified 37 times until the user finally figures it out. *low priority*
Also seek to catch any edge cases where an argument, ie: trackers, does not modify correctly.

Fix edit-args

---

src/trackermeta.py

Limits the amount of screenshots used from a sourced tracker to the amount set in the config file.
Also cleaned up the output of the image validation.

Limit used screenshots to config option

---

data/example-config.py
src/rehostimages.py
src/takescreens.py
src/trackers/COMMON.py
src/trackers/PTP.py
src/uploadscreens.py
upload.py

I went down the task spawning route originally as I was having trouble with async calls and imgbox.
takescreens does not have that problem. The issue with consoles becoming non-responsive _may_ be due to the ffmpeg sub-processes that were being spawned, maybe not.
will figure out how to handle imgbox

Image handling update

---

src/trackers/MTV.py

I suggest to keep AKA in MTV uploads titles:
- The rules are not against it. And indirectly even encouraging it, cause AKA makes torrents easier to find there (see 5.3).
- There ara plenty of verified by staff uploads with AKA in titles.

Update MTV.py: no AKA removing

---

src/trackers/SHRI.py

I modified the code in such a way that it recognizes the languages of the audio tracks and writes them in the title. I also changed ENCODE's id.

Add language check and chande encode ID

---

src/prep.py

Added SP service check for 720p, similar to 1080p, half the bitrate for CR.
CR 720p = 4000kbps
HIDI 720p = 2000-2500kbps, basically always less than 4000kbps.

Update SubsPlease-specific checks for 720p

---

data/example-config.py
data/templates/user-args-template.json
src/prep.py
src/takescreens.py

Currently only TMDB supported.
You should probably only override args that are not strictly tied to metadata, like `--no-aka`  or other `--no` type args.
Other examples would be `--manual_frames`, any of the description handling.
The user-args.json should follow this formatting style
```python
{
"entries": [
{
"tmdb_id": "tv/12345",
"args": [
"--no-aka",
"--screens", "4"
]
},
{
"tmdb_id": "tv/54321",
"args": [
"--no-year",
"--personalrelease",
"--descfile", "path_do_desc_file"
]
}
]
}
```

Allow some hardcoded user overrides

---

src/trackers/HUNO.py

The tracker does not accept "Blu-ray" as a source, only "BluRay", even if it is a Full Disk release.

Catch HUNO BluRay naming requirement

---

data/example-config.py
src/tmdb.py
src/trackers/COMMON.py

Credits to Uploadrr which already has this feature and made me want to implement it here.
What this PR does:
- Adds 2 config options to control whether to pull logos from TMDB, and the logo size.
- If enabled, it will pull the first logo for the TV/Movie from TMDB using the `/{tmdbId}/images` endpoint and place it at the top of the BBCode description.
By default the option is disabled and no extra requests are sent to TMDB.
What it looks like:
Let me know if this is unwanted or what can be made to improve it if necessary. 
Cheers!

feat: pull logo from tmdb

---

src/tmdb.py

Fixing a bug from my previous PR that I failed to catch.
When no matching logo is found, the function returns the default value of `None`, but on [COMMON.py#L93](https://github.com/Audionut/Upload-Assistant/blob/master/src/trackers/COMMON.py#L93) I was checking if the value is != from an empty string, which it is and then the logo is displayed as `[img]None[/img]`.
For this fix I decided to have it fall in line with whats already done for `backdrop` and `poster_path` and have the default return be an empty string instead of `None`

fix: logo displayed as None

---

src/args.py
src/prep.py

When the argument is set, we can safely run `get_season_episode`, which is required to run the newly added episode functions.
These episode snatching functions have been added to async calls when:
`if int(meta['imdb_id']) != 0 and int(meta['tvdb_id']) != 0:` or
`elif int(meta['imdb_id']) != 0 and int(meta['tmdb_id']) != 0:`
Significantly speeding episode data retrieval.
The argument is a good use case with `https://github.com/Audionut/Upload-Assistant/blob/master/data/templates/user-args-template.json`

add argument --not-anime

---

src/trackers/HUNO.py

The tracker does not allow the region code in the name.

HUNO - remove region from name

---

src/takescreens.py

Title says all.
Example of 2160p screenshot without the proposed modification:
Example of 2160p screenshot with the proposed modification:

Adjust font size of screenshot overlays to match the resolution.

---

src/tvdb.py

Removed line 273 (any reason to increment `absolute_episode_count` by 1?), grab absolute ep from payload instead.
Tested with One Piece S22 and Solo Lvling S2 from SubsPls

Correct absolute episode number lookup

---

src/args.py

Without the proposed modification, it was necessary to provide an absolute path for the description file.
The proposed commit removes that necessity and adds the possibility of providing a relative path, as in:
`upload video.mkv -df description.txt -tk BLU`

Accept both relative and absolute path for the description filename.

---

data/example-config.py
src/args.py
upload.py

Existing meta.json is more problematic then useful.
Now that uploaded image links are safely stored in `image_data.json` (rehosted images for sites have their own file), it's time to put an end to all problems associated with existing data.

Clean existing meta

---

src/trackers/HDB.py

A typo prevented UA to set automatically the 'Internal' tag on HDB.
I made an upload of an internal encode on HDB to check that it now works with this candidate pull request. :)

Correct typo to enable UA to set the 'Internal' tag on HDB.

---

src/trackers/PTP.py

I propose to comment out that line. While I understand that it may prove useful in some cases, it has a very bad side effect. 
If you are an encoder, you will likely want to add some script (AviSynth, VapourSynth) in your description. In that case, you will want to enclose your script in `[code]...[/code]` so that unwanted emojis do not show up in your script and to have your script rendered in a nice monospaced font.
That line systematically convert the `[code]...[/code]` around your script into `[quote]...[/quote]`, so I propose to comment it out.

In PTP descriptions, do not replace [code] by [quote].

---

src/trackers/HDB.py

HDB does not have the `[code]...[/code]` blocks, but it is probably better to convert them to `[font=monospace]...[/font]`blocks than to `[quote]...[/quote]`blocks.

In HDB descriptions, do not replace [code] by [quote].

---

data/example-config.py
src/trackers/COMMON.py

Changed a few aspects of how the Description is formatted.
1. Fixed a bug in COMMON.py where the screenshot header, if provided, would appear after the first file name when uploading multiple files.
2. Added an option in the default section of the config for a custom description header. I also added this as an option under each tracker in the configuration. Edited COMMON.py to check if the tracker has a custom header in the config; if not, it is the custom header in the default set; if not, fall back to original logic and desc header from tracker.py. Logic is Config.Tracker.custom_description_header > Config.default.custom_description_header > COMMON.py.unit3d_edit_desc(desc_header)
3. Added an option for custom signature per tracker in the config file. Edited common.py to use tracker …

Description Customization

---

data/example-config.py
src/bluray_com.py
src/prep.py
src/rehostimages.py
src/trackers/COMMON.py
src/uploadscreens.py
upload.py

Automated bluray region-distributor parsing

---

src/trackers/OTW.py
src/tvdb.py

> NOTE: For TV series, the Year in the title should be the year that the series premiered, not necessarily the year in which a particular season or episode aired. 
https://oldtoons.world/pages/1

OTW - use year in TV title

---

src/trackers/HDB.py

When you upload your own encode to HDB, you will likely add comparisons between source/filtered/encode in your description. In that case, you don't need to include additional screenshots, so you will want to use the "-s 0" option in UA.
But, up to now, this was adding the line:
"error: Upload failed - no images received"
at the end of the uploaded description.
This PR aims at handling this (somewhat specific) case more smoothly.
Tested in debug mode.

Allow '-s 0' option when uploading to HDB

---

src/trackers/CBR.py

Detect and categorize audio languages as ` DUAL` (for 2 languages) or ` MULTI` (for 3 or more languages) based on the MEDIAINFO.txt

CBR: Refactor get_audio function to handle multiple languages

---

src/add_comparison.py
src/args.py
src/trackers/BHD.py
src/trackers/COMMON.py
src/trackers/HDB.py
src/trackers/PTP.py
upload.py

~~Only PTP for now~~, see discussion in https://github.com/Audionut/Upload-Assistant/pull/485
I'm open to renaming or other handling of `-comps_index`
`py upload.py "path_to_movie" -comps "path_to_folder_containing_comparisons" -comps_index X` where X is the index of your upload.
As an example:
```
01-1-Source.png
02-1-Source.png
01-2-Filtered.png
02-2-Filtered.png
01-3-SoLaR.png
02-3-SoLaR.png
01-4-DON.png
02-4-DON.png
```
`-comps_index 3` would index the SoLaR images as the main images.

Add comparison images

---

data/example-config.py
src/trackers/ULCX.py

Hopefully this could end up on more unit3d trackers soon but for now it's available here.

(Add) mod queue opt-in option to ULCX tracker

---

src/trackers/BHD.py
src/trackers/BLU.py
src/trackers/COMMON.py
src/trackers/HDB.py
src/trackers/PTP.py

When you do an encode, the general idea is now to have a folder with all the comps AND a generic description file using a superset of all the bbcodes formats. Then, you can upload to an arbitrary tracker and let UA do its magic in formatting both the description and the comparisons for the intended tracker.
This PR adds some bbcode formatting of a generic description file for PTP/HDB/BHD/BLU.
Tested with a generic description file and a comparison folder in debug mode on PTP/HDB/BHD/BLU.

Additional bbcode editing on PTP/HDB/BHD/BLU

---

src/bbcode.py

Previously convert_comparison_to_centered was converting:
```
[comparison=    AUS spectrogram               ,         USA spectrogram            	]
```
(which is perfectly handled by PTP, for example)  into
```
[center]AUSspectrogram | USAspectrogram
```
With the submitted PR, inner spaces in names will now be preserved:
```
[center]AUS spectrogram | USA spectrogram
```

Stop convert_comparison_to_centered to crush spaces in names

---

src/prep.py
src/tmdb.py

I found an IMDB that was returning both movie and tv results. Why........
Changed the function to rely on tvdb id first, then use category.
Stops IMDB/TVDB from BTN becoming category `movie` with the wrong TMDB

tmdb from imdb updates

---

requirements.txt
src/imdb.py
src/tmdb.py

Something must have changed I guess, since the old cinemagoer results never returned year, which meant this function would never return anything.
Updated the function to use graphAPI, and updated the tmdb searching function to try searching imdb first before asking for a tmdb id.
Prints name, year, id, type, plot and allows user to select which imdb to use. Then uses imdb for tmdb,

Make search imdb not useless

---

src/edition.py
src/imdb.py
src/prep.py

guessit, blessit, has always been useless for edition information for me.
This PR adds imdb edition information from the existing call, and matches runtime to set edition. Automagically because I'm lazy with args.
It should also automagically match all editions from multi-disc bdmv.

Get edition from IMDB

---

requirements.txt
src/clients.py

It's used once, for what amounts to a glorified `dict` or `NamedTuple`.
Just use a `dict`...

Remove 'pyrobase' requirement

---

src/video.py

If you have another suggested value different than 24 pls let me know.
Fails due to empty string casting to int
error logs:
```
Gathering info for Dragon Knight 4
Error in gather_prep: list index out of range
Traceback (most recent call last):
File "/Upload-Assistant/upload.py", line 97, in process_meta
meta = await prep.gather_prep(meta=meta, mode='cli')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Upload-Assistant/src/prep.py", line 277, in gather_prep
meta['resolution'], meta['hfr'] = await get_resolution(guessit(video), meta['uuid'], base_dir)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Upload-Assistant/src/video.py", line 172, in get_resolution
framerate = mi['media']['track'][1].get('FrameRate', '')
~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out …
```

Set default value for FrameRate

---

src/args.py
src/imdb.py
src/metadata_searching.py
src/prep.py
src/tmdb.py
src/tvdb.py
src/tvmaze.py

When no imdb/tmdb input, attempts to grab that data before the concurrent retrieval functions. Doesn't save as much time as I was hoping, but a noticeable effect in any event.
Put the episode data retrieval behind the `episode_overview` config, since if False, that data is not needed and just slows the process. TVDB is unaffected if the keys are present, since that provides other benefits.
Don't return early if there is a TMDB lookup error, try the other methods instead.

refactor id handling

---

upload.py

My backspace just breaks/stopped working after running UA. This has been going on for a while but I got some free time to look into this. 
My current terminal has this:
```
$ stty -a
...
intr = ^C; quit = ^\; erase = ^H;
...
```
after running `upload.py`, the output changed to this (note `erase`):
```
$ stty -a
...
intr = ^C; quit = ^\; erase = ^?;
...
```
UA somehow changed my `erase` key to `^?` and `stty sane` restored it to default correctly, but it does not stick, pressing `backspace` and I'll get `^H` in my terminal again. By explicitly forcing it and set it to `^H`, the config stuck and backspace behavior was returned to normal. Also works on Windows (try typing Ctrl + H in `cmd`, it will do backspace).

Explicitly restore backspace character (^H)

---

src/is_scene.py

Fixes a bug that caused a crash in the `is_scene` function.
The `is_all_lowercase` variable was not being initialized if the input filename didn't have an extension, causing an `UnboundLocalError`.
I've initialized it to `False` at the start of the function to prevent this.

is_scene - Fix crash when is_all_lowercase is not defined

---

data/example-config.py
src/trackers/ASC.py
src/trackerstatus.py

- Changes the way anonymous uploads are handled; it no longer interrupts the user and instead just prints a warning.
- Fixes an issue where the tracker would detect a duplicate if multiple users were uploading with the tool simultaneously. Using the infohash as the filename is likely the best way to prevent this.
- Fixes an issue where the site's database would throw a silent error when titles contained non-ASCII characters.

ASC - changes and fixes

---

src/tmdb.py

Prevents errors when the imdb_id string is "None" by converting it to an empty string.
This ensures that the subsequent check to convert to integer does not fail, and that the imdb_id is correctly treated as missing.

Handles "None" imdb_id string

---

src/trackers/DC.py

The website has a CSP that only allows images from:
- https://img.digitalcore.club
- https://i.imgur.com
- https://i.postimg.cc
- https://beyondhd.co
- https://images2.imgbox.com
- https://thumbs2.imgbox.com
- https://i.ibb.co
- https://image.tmdb.org
Out of these, UA only supports imgbb and imgbox, so we keep those.

Add image restriction to DigitalCore

---

upload.py

Current `upload.py` is looking for `discord` (all lowercase) from `config.py` while Discord config section is `DISCORD`, therefore, `use_discord` is always `False`. This fix will now follow the `use_discord` key from `config.py`

Get correct discord config in upload.py

---

src/get_tracker_data.py

I'm having an issue where the distributor and region information is missing because it's matching HUNO first. Since HUNO doesn't store region and distributor IDs, the final metadata ends up without this information, even though there are other IDs in the client from sites that do store it (like BLU).

get_tracker_data.py - lower HUNO priority

---

src/trackers/BHD.py
src/trackers/COMMON.py

Like what was done with BHD screenshots (consistent spacing between screenshots, 1 space between columns, 1 space between lines), the same will apply to other UNIT3D trackers as well: https://slow.pics/c/vJ7frGJb

Give screenshots some spaces to breathe

---

src/metadata_searching.py
src/prep.py

Add handling for essential TMDB,  to allow a retry before failure.
With multiple ID input, this will result in 3 retires before failure, allowing continued operation with brief WAN failure.

TMDB retry

---

src/trackers/AL.py

The `await self.get_mal_data` function will crash anyways if the ID is None.

Skip torrents for AL if they don't have a MAL ID

---

src/trackers/SP.py

Seedpool has updated their media categories. This PR updates the SP category logic to match the new tracker category revisions
- Remove TV Pack/Boxset category (goes to TV now)
- Only send TV to the Anime category. Movies will go to the Movies category under Movies/Other

fix: update SP category logic

---

data/example-config.py
src/trackers/COMMON.py
src/trackers/DC.py
src/trackers/TL.py

I noticed that sometimes DC wasn't registering all my seeded torrents, so I figured it was the missing proxy announce link when uploading torrents via UA. 
These changes allow you to add an announce list to trackers that require it.
This also changes the DC announce link because it appears to have changed, although the old one still works.

add support for multiple announce links

---

data/example-config.py
src/trackers/DC.py

DC updated its API a few hours ago:
```
How to use your API Key
Authentication
HTTP Headers (recommended):
X-API-KEY: YOUR_API_KEY
Authorization: Bearer YOUR_API_KEY
Authorization: ApiKey YOUR_API_KEY
Query String:
?apikey=YOUR_API_KEY
?api_key=YOUR_API_KEY
POST Body (form-data or x-www-form-urlencoded):
apikey=YOUR_API_KEY
api_key=YOUR_API_KEY
Allowed API Routes:
GET /api/v1/torrents – List torrents
GET /api/v1/torrents/search – Search
GET /api/v1/torrents/torrents_exact_search – Exact search
POST /api/v1/torrents/upload – Upload torrent
GET /api/v1/torrents/download/<torrentid> – Download torrent file
Examples:
curl -H "X-API-KEY: YOUR_API_KEY" https://digitalcore.club/api/v1/torrents
curl -H "Authorization: Bearer YOUR_API_KEY" …
```

DC - API update

---

src/exportmi.py
src/prep.py
src/video.py

In cases where UA is executed too early before the download finishes or there's an issue with the file, warn users to double-check before proceeding with upload.
Not sure if there's a situation where conformance errors could be wrongly reported by MediaInfo, hence this is just a warning, not a hard stop.
Example:
```
General
Unique ID                                : 114357455792027941594255263657427451072 (0x560871E18497749080468D06DC2FBCC0)
Complete name                            : C:\Users\ppkho\Downloads\[WakuTomete] Princess Session Orchestra - 18 (WEB 1080p AVC E-AC3) [3D7914C2].mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 877 MiB
Duration …
```

Catch conformance error from mediainfo and warn users

---

config-generator.py

New image hosts were added to the config as image_host_1 instead of img_host_1
None values in example_config were being set to null and creating an invalid config.py
Affected values: "emby_dir", "emby_tv_dir"
This fixes both of these.

Fix img_host and None types

---

data/example-config.py
requirements.txt
src/languages.py
src/trackers/AVISTAZ_NETWORK.py
src/trackers/AZ.py
src/trackers/CZ.py
src/trackers/PHD.py
upload.py

- Use `MediaInfo.json` for language detection and processing  
- Fix handling of SD content for AZ/CZ  
- Adjust codec naming when release includes encoding settings (e.g., H. → x.)  
- Fix positional argument handling when adding media to the site database  
- Add missing countries
- Make basic rule checking optional  
- fix Chinese language mapping
- Update the cookie file after a successful request, as they change with time. This persists the latest session state and handles cookie renewals from the server.
- Add Internal tag
- Remove the option to skip image rehosting. Screenshots should always be hosted on AZ sites.

fix(AvistaZ sites) - languages, resolution, naming, rules

---

src/trackers/HUNO.py

Bit rate can look like this: `5 999 kb/s`
In this example, the regex matches only `999` so the check fails.

Fix HUNO bit rate detection

---

src/audio.py

An "Isolated Score" with "zxx" language is viewed by UA as "non english - non commentary", making UA tagging the corresponding remux/encode as "Dual Audio" and therefore preventing the upload on some trackers.
This PR informs UA that "zxx" (that is, "No linguistic content") is not a foreign language.

Refine dual-audio detection for zxx

---

upload.py

If nothing is entered (just pressing Enter) when prompted to correct input arguments, the program will crash with the below error. This is a simple fix to have the program safely handle when there is nothing entered, and just use the previous arguments.
```
Is this correct? y/N: n
:: Input args that need correction e.g. (--tag NTb --category tv --tmdb 12345)
>
An unexpected error occurred: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
File "/opt/Upload-Assistant/upload.py", line 785, in do_the_thing
await process_meta(meta, base_dir, bot=bot)
File "/opt/Upload-Assistant/upload.py", line 233, in process_meta
editargs = tuple(editargs.split())
^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

Fix crash when no edit args provided (handle no/empty input safely)

---

src/trackers/YUS.py

Give it the same arguments in UNIT3D base otherwise there will be error:
```
An unexpected error occurred: YUS.get_type_id() got an unexpected keyword argument 'mapping_only'
Traceback (most recent call last):
File "/Upload-Assistant/upload.py", line 917, in do_the_thing
await tracker_setup.tracker_request(meta, meta['trackers'])
File "/Upload-Assistant/src/trackersetup.py", line 780, in tracker_request
results = await asyncio.gather(*)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Upload-Assistant/src/trackersetup.py", line 620, in process_single_tracker
type_mapping = await tracker_instance.get_type_id(meta, mapping_only=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: YUS.get_type_id() got an unexpected keyword argument …
```

Fix YUS get_type_id

---

src/uphelper.py

Perhaps the region is unnecessary, since it is in the name? But the distributor is quite useful, as it is not shown anywhere before the upload.

feat: add region and distributor information to get_confirmation

---

src/trackers/PTP.py

[code] and [quote] blocks have different use cases and are both useful in PTP descriptions.
They should coexist, imo.

Both [code] and [quote] should coexist in PTP descriptions
